### ISSUE TITLE
Add partner logos to the project

### ISSUE THREAD

**Issue by vrooje** [zooniverse/First-Responders#12]
QCRI, Planet Labs need logos on the project. Digital Globe does too as they've provided before images.

**Comment by vrooje** [comment]
![planet-labs](https://cloud.githubusercontent.com/assets/2357126/5697503/8099bb76-99a7-11e4-93a4-e7312586fef1.png)

Planet Labs logo (from their press website)

By the way, I don't have a preference for what the names of these images should be... I figure they should be displayed below the spotter's guide but above our footer...

**Comment by vrooje** [comment]
![dg_foundation_logo](https://cloud.githubusercontent.com/assets/2357126/5702580/ae118b9a-9a53-11e4-9741-75daf5ee1201.png)

The Digital Globe Foundation image...

I'm not completely clear where to put these. @brian-c ? Ideally it'd be something like right above the footer, but there isn't really a container there. If we added it to the bottom of the spotters guide that would be pretty hacky but it might work?

For clarification, QCRI and Planet Labs are our overall partners so we should mention them (the logos should be roughly equally sized, I think), and the DG foundation provided pre-crisis images so we need to give them credit. I'll ask Kate about the proper attribution for the post-crisis UAV images but in the meantime we should add the other logos, and I'm flexible on where as long as it doesn't mean people have to scroll farther to get to the spotter's guide info....

**Comment by brian-c** [comment]
Can they go on the team page?

**Comment by vrooje** [comment]
They probably should go there too but the DG images should be credited on the same page they're used (text credit is okay).

**Comment by vrooje** [comment]
Looks great -- Heather from QCRI has pointed out that we should add links and text below each logo as well. Do you want me to add that directly or should we put the text in as comments here?

**Comment by brian-c** [comment]
Go ahead and add the descriptions. I fixed the links and uncommented the descriptions in project.coffee.

**Comment by vrooje** [comment]
Okay. Heather from QCRI may add a description here but I'll add the others for now.

**Comment by vrooje** [comment]
I haven't yet gotten any text from others; can we deploy this today so that there's at least some text there?

**Comment by brian-c** [comment]
Deployed now.

**Comment by vrooje** [comment]
Thanks. I've also made minor edits to fix a couple of typos but those can wait until the next deploy for other purposes. For now I'm closing this as I have no idea when edits to the text might come in from partners.
