### ISSUE TITLE
Create PRN Talk

### ISSUE THREAD

**Issue by vrooje** [zooniverse/First-Responders#16]
Yep, even for the beta. This project is a little unusual as we'd like to see the effect of Talk in the beta, plus give experienced digital humanitarians who've never used Zooniverse the opportunity to try it out before a live deployment.

Not sure whether this is @parrish or @chrissnyder ?

Also not sure how important it is to carry over #14 into this, perhaps by renaming "Favorites" to "Saved Tiles" or similar. If that's very difficult to do perhaps it's not worth it. Thoughts, @mrniaboc @chrislintott ?

**Comment by chrissnyder** [comment]
Deployed.

Not sure about the second point. Changing text on Talk is a bit hacky, but if it's decided we need to change it, I'll look into it.
