### ISSUE TITLE
Talk Roles need to be created + assigned

### ISSUE THREAD

**Issue by vrooje** [zooniverse/First-Responders#22]
Admin and Moderator as usual - I should be an admin so I can assign roles etc. No mods yet...
plus: 
- Zooniverse Team (Darren/dzm, Grant/mrniaboc etc - including Rob/ttfnrob, other dev team?)
- PRN Team (Me/vrooje, Chris/zookeeper, external partners if I get their Zooniverse usernames)

**Comment by chrissnyder** [comment]
Done. @DarrenMcRoy will need to make an account, as Talk is hosted off of dev.

**Comment by DarrenMcRoy** [comment]
Actually, it looks like my current account works just fine! Has the Zooniverse Team tag and all.

**Comment by DarrenMcRoy** [comment]
However @chrissnyder, it looks like I don't have the ability to create a new board! Trying to set up the boards, and it give me the interface, but when I click New Board, the button just goes gray and nothing happens.

![screen shot 2015-01-12 at 10 50 50 am](https://cloud.githubusercontent.com/assets/8987864/5706750/e708275c-9a48-11e4-92f6-d335dec1110a.png)
