### ISSUE TITLE
The background is a big plus

### ISSUE THREAD

**Issue by ttfnrob** [zooniverse/First-Responders#23]
The background image of a giant medical cross is a bit distracting and blocky. How about something more 'planetary' e.g. http://upload.wikimedia.org/wikipedia/commons/4/4d/Iss007e10807_darker.jpg (which is Wikimedia commons too).

i.e. 

![screen shot 2015-01-12 at 14 57 21](https://cloud.githubusercontent.com/assets/83192/5704659/7a3cf468-9a6b-11e4-9f01-f4d418893866.png)

**Comment by mrniaboc** [comment]
I like that a lot more!

**Comment by vrooje** [comment]
Me too! And I bet Planet Labs will love it.

**Comment by vrooje** [comment]
Gorgeous.
