### ISSUE TITLE
Change "OK" --> "Close" in structural damage menu

### ISSUE THREAD

**Issue by vrooje** [zooniverse/First-Responders#32]
A user on Talk has noted ( http://talk.planetaryresponsenetwork.com/#/boards/BFR0000002/discussions/DFR000001y ) that over time clicking the word "OK" after rating buildings as severely damaged is negatively affecting him/her.

If this were a science project I'd be skeptical, but in this case we should be very sensitive to subtle things that might affect the mental health of our volunteers. Can we change this word to "Close" (or similar, but probably not "Done") instead of "OK"? 

I didn't see it in project.coffee so this is probably something @brian-c should do as I don't want to accidentally break the live project.

**Comment by DarrenMcRoy** [comment]
I agree with this sentiment... it could be particularly cognitively dissonant after a disaster that just happened a day or two ago, too. It's a simple change and doesn't sacrifice any communication.

**Comment by chrislintott** [comment]
Please record when it’s changed on the live site so we can check for a change in behaviour

C

**Comment by brian-c** [comment]
> It's a simple change

Looks like it would be, but nope.

I'm on this now.

**Comment by vrooje** [comment]
Thanks. Funny how often the apparently simple fixes are really difficult
(and sometimes vice-versa)...

**Comment by brian-c** [comment]
**Deployed to beta just now, 14 Jan at 11:15.**

**Comment by vrooje** [comment]
Out of an overabundance of clarifying that's GMT/UTC, the same time zone our classifications are timestamped in (at least in other projects)...
