### ISSUE TITLE
Tutorial needs to be checked over (then created)

### ISSUE THREAD

**Issue by vrooje** [zooniverse/First-Responders#6]
Text for a tutorial is here:
https://docs.google.com/document/d/1PvQRgAlf-BZP47zFhQNKXo6AIBzD3ExHk2FCZBLThTg/edit?usp=sharing

Comments & suggestions welcome.

**Comment by vrooje** [comment]
Tutorial looks great -- Might tweak the text etc but all the mechanics are there.

However, it's still loading a random image instead of the 2 above; can we fix that?

**Comment by brian-c** [comment]
Added a tutorial subject.

@chrissnyder can you fill in the appropriate IDs in the [load-tutorial-subject](https://github.com/zooniverse/First-Responders/blob/151aeeaff4fd3b5a38abe0f0f41c09d06e7c3c86/load-tutorial-subject.coffee) module?

**Comment by chrissnyder** [comment]
Whoever created the project/workflows created them with the same ID, hence why it's like that on the tutorial subject.

**Comment by brian-c** [comment]
Weird. I thought that was impossible with BSON IDs.
