### ISSUE TITLE
Spotter's Guide Needs to be filled out

### ISSUE THREAD

**Issue by vrooje** [zooniverse/First-Responders#8]
Draft lives at https://docs.google.com/document/d/1BUU0nyxaXUkXTsCaH_jLwkUnonZHnq2SRsuAyBK4yNY/edit?usp=sharing

Example images also needed.

**Comment by vrooje** [comment]
Spotter's guide text is in field-guide.coffee, but it's not loading at the bottom of the classification page. Hoping we can get this in by the beta on Monday...

**Comment by brian-c** [comment]
Just pushed the text. Still no images.

I can access the directory, but it's empty for me.

**Comment by vrooje** [comment]
That's weird... I'll re-upload and also e-mail them. Sorry about that.

**Comment by vrooje** [comment]
Looks great!
